# Generated by Django 3.1 on 2020-08-23 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('univer', '0003_auto_20200821_0756'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='position',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='code',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='first_n',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='last_n',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='middle_n',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='position_one',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='position_two',
        ),
        migrations.AddField(
            model_name='employee',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='position',
            name='code',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='position',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_id', to='univer.employee'),
        ),
    ]
