# Generated by Django 3.1 on 2020-08-23 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('univer', '0004_auto_20200823_0742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee', to='univer.employee'),
        ),
    ]
