# Generated by Django 3.1 on 2020-08-23 18:24

from django.db import migrations, models
import django.db.models.deletion
import univer.models


class Migration(migrations.Migration):

    dependencies = [
        ('univer', '0005_auto_20200823_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee', to='univer.employee', validators=[univer.models.number_employee]),
        ),
    ]
